version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: sporthack-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sportstore
    volumes:
      - db_data:/var/lib/mysql
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    container_name: sporthack-backend
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=sportstore
      - VULNERABLE=true
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: sporthack-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  db_data: