name: Deploy React App to GitHub Pages

on:
  workflow_run:
    workflows: ["Docker CI - SportHack Store"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Download frontend artifact
      uses: actions/download-artifact@v3
      with:
        name: frontend
        path: ./frontend

    - name: Install Node (for deploy script)
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Deploy to GitHub Pages
      working-directory: ./frontend
      run: |
        npm install gh-pages
        npm run deploy
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
